version: "3.8"
services:
    mysql-db:
        image: mysql
        container_name: mysql_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - service-network

    zookeeper:
        image: zookeeper
        ports:
            - "2181:2181"
        networks:
            - service-network

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:9093,INTERNAL://:9092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_CREATE_TOPICS: "test:1:1,messages:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends_on:
            - zookeeper
        networks:
            - service-network

    order-management-www:
        build: docker/php
        container_name: order_symfony
        ports:
          - "8600:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./services/order-management/:/var/www
        restart: always
        networks:
            - service-network
    service-www:
        build: docker/php
        container_name: service_symfony
        ports:
          - "8601:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./services/service/:/var/www
        restart: always
        networks:
            - service-network

networks:
    service-network:

volumes:
    db-data:
    
