version: "3.8"
services:
    mysql-db:
        image: mysql
        container_name: mysql_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - service-network



    order-management-www:
        build: docker/php
        container_name: order_symfony
        ports:
          - "8600:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./services/order-management/:/var/www
        restart: always
        networks:
            - service-network
    service-www:
        build: docker/php
        container_name: service_symfony
        ports:
          - "8601:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./services/service/:/var/www
        restart: always
        networks:
            - service-network

networks:
    service-network:

volumes:
    db-data:
    
